#!/bin/bash

scriptPath="/Library/Application Support/Scotch/Scripts"
myScript="${scriptPath}/ReconAtLogin.sh" 
daemonPath="/Library/LaunchDaemons/au.edu.wa.scotch.ReconAtLogin.plist"

if [[ -d "${scriptPath}" ]] 
then
	echo "${scriptPath} exists."
else
	echo "Script path not found, creating"
	sudo mkdir -p "${scriptPath}"
fi

tee "${myScript}" <<\EOS
jamfBin="/usr/local/jamf/bin/jamf"
launchdLog="/private/var/log/scotch-agents.log"
touch ${launchdLog}
function enterLog () {
	theDate=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[${theDate}] ${1}" >> "${launchdLog}"
}
dateTag=$(date '+%Y-%m-%d %H:%M:%S')
dockStatus=$(pgrep -x Dock)
enterLog "Starting script"
enterLog "Checking for Dock process"
while [ "$dockStatus" == "" ]; do
  enterLog "Desktop not loaded, waiting 10..."
  sleep 10
  dockStatus=$(pgrep -x Dock)
done
enterLog "Dock is loaded, moving on"

if [[ $(${jamfBin} checkJSSConnection -retry 12 > /dev/null; echo $?) -gt 0 ]] # Retry count - 12*5=60s
then
	enterLog "Failed JSS connection test, unable to recon at login."
else
	enterLog "JSS connection successful, running recon..."
	${jamfBin} recon
	enterLog "Login recon successful"
fi
EOS

tee "${daemonPath}" << EOD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>au.edu.wa.scotch.ReconAtLogin</string>
	<key>ProgramArguments</key>
	<array>
		<string>sh</string>
		<string>-c</string>
		<string>/Library/Application\ Support/Scotch/Scripts/ReconAtLogin.sh</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
    <key>StandardErrorPath</key>
    <string>/private/var/log/scotch-agents.log</string>
    <key>StandardOutPath</key>
    <string>/private/var/log/scotch-agents.log</string>
</dict>
</plist>
EOD

chown root:wheel "${daemonPath}"
chmod 644 "${daemonPath}"
chmod 755 "${myScript}"
chmod +x "${myScript}"
